name: "🐛 Bug"
description: "Something broke or behaves unexpectedly."
title: "bug: <short summary>"
labels: [bug, needs triage]
body:
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - S1 - Critical (crash/data loss)
        - S2 - Major (feature unusable)
        - S3 - Minor (workaround exists)
        - S4 - Cosmetic
    validations: { required: true }

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: "Describe the bug and why it’s a problem."
      placeholder: "Clear description of the unexpected behavior"
    validations: { required: true }

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: "Numbered steps help a lot."
      placeholder: "1) …  2) …  3) …"
    validations: { required: true }

  - type: textarea
    id: expected
    attributes:
      label: Expected result
      placeholder: "What you expected to happen"
    validations: { required: true }

  - type: input
    id: env_version
    attributes:
      label: App version / Git commit
      placeholder: "e.g. v1.0.2 or 9f8ab12"
    validations: { required: true }

  - type: checkboxes
    id: env_os
    attributes:
      label: Environment
      options:
        - label: Windows
        - label: macOS
        - label: Linux
    validations: { required: false }

  - type: textarea
    id: logs
    attributes:
      label: Logs / stacktrace (optional)
      render: shell
      placeholder: "Paste the relevant log excerpt"

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: "Paste image URLs or drag & drop in the comment after creating the issue."
