name: Checkstyle (lint)

on:
  pull_request:
    branches: [ main, develop, 'feature/**', 'release/**' ]
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Run Checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      - name: Install (skip tests)
        run: mvn -B -DskipTests install

      - name: Checkstyle
        run: mvn -B checkstyle:check

      - name: Upload Checkstyle XML
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/checkstyle-result.xml
