name: CI

on:
  push:
    branches: [ main, develop ]
    paths-ignore: [ '**.md', 'docs/**', '.gitignore' ]
  pull_request:
    branches: [ main, develop, 'feature/**', 'release/**' ]
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    name: Unit tests + coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      - name: Run tests with JaCoCo
        run: mvn -B clean test jacoco:report

      - name: Upload test reports (JUnit + JaCoCo)
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            target/surefire-reports/**
            target/site/jacoco/**

  package:
    name: Build JAR (if tests pass)
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      - name: Package (skip tests)
        run: mvn -B package -DskipTests

      - name: Upload app artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: target/*.jar
