name: Mutation Testing (PIT)

on:
  push:
    branches: ["feature/**", "fix/**", "hotfix/**", "develop", "main"]
  pull_request:
    branches: ["develop", "main"]

jobs:
  pitest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      # If PIT is configured in the POM, this command will use that configuration.
      - name: Run PIT
        run: mvn -B -DskipTests=false org.pitest:pitest-maven:mutationCoverage

      - name: Upload PIT report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pit-report
          path: |
            **/target/pit-reports/**
