name: Release: tag & upload JAR

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

permissions:
  contents: write

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine version from branch name
        id: ver
        run: |
          BRANCH="${{ github.event.pull_request.head.ref }}"
          if [[ "$BRANCH" =~ ^release\/([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "version=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "Branch name must be release/x.y.z"; exit 1
          fi

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      - name: Build package
        run: mvn -B -DskipTests package

      - name: Create Release
        id: create
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.ver.outputs.version }}
          name: v${{ steps.ver.outputs.version }}
          body: "Automated release for ${{ steps.ver.outputs.version }}"
          draft: false
          prerelease: false

      - name: Upload JAR asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create.outputs.upload_url }}
          asset_path: target/*.jar
          asset_name: app-${{ steps.ver.outputs.version }}.jar
          asset_content_type: application/java-archive
