name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build (tests included)
        run: mvn -B -DskipTests=false package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/*.jar
          generate_release_notes: true
