name: Telemetry
on:
  workflow_run:
    workflows: ["CI", "Checkstyle (lint)", "Mutation Testing (PIT)"]
    types: [completed]

jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Compute metrics
        id: m
        uses: actions/github-script@v7
        with:
          script: |
            const run = context.payload.workflow_run
            const durationMs = Date.parse(run.updated_at) - Date.parse(run.run_started_at)
            const minutes = Math.round(durationMs / 600) / 100
            const obj = {
              repo: `${context.repo.owner}/${context.repo.repo}`,
              workflow_id: run.workflow_id,
              workflow_name: run.name,
              run_id: run.id,
              run_number: run.run_number,
              run_attempt: run.run_attempt,
              event: run.event,
              conclusion: run.conclusion,
              status: run.status,
              head_branch: run.head_branch,
              head_sha: run.head_sha,
              actor: run.actor && run.actor.login,
              created_at: run.created_at,
              run_started_at: run.run_started_at,
              updated_at: run.updated_at,
              duration_ms: durationMs,
              duration_min: minutes
            }
            const fs = require('fs')
            fs.writeFileSync('metrics.json', JSON.stringify(obj, null, 2))
            core.setOutput('minutes', String(minutes))
      - name: Summary
        run: |
          echo "### Telemetry for ${{ github.event.workflow_run.name }}" >> $GITHUB_STEP_SUMMARY
          echo "- conclusion: **${{ github.event.workflow_run.conclusion }}**" >> $GITHUB_STEP_SUMMARY
          echo "- duration (min): **${{ steps.m.outputs.minutes }}**" >> $GITHUB_STEP_SUMMARY
      - name: Upload metrics artifact
        uses: actions/upload-artifact@v4
        with:
          name: metrics-${{ github.event.workflow_run.id }}
          path: metrics.json
