name: Telemetry

on:
  workflow_run:
    workflows: ["CI", "Checkstyle (lint)", "Mutation Testing (PIT)"]
    types:
      - completed

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Log CI run data
        run: |
          echo "Workflow: ${{ github.event.workflow.name }}"
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Run ID: ${{ github.event.workflow_run.id }}"
